"""Writes supabase/test.bundle.sql: one transaction that rebuilds the schema, runs test.sql and rolls back.
Paste the output file into the Supabase SQL editor. It never commits anything."""
from pathlib import Path
here = Path(__file__).parent
schema = (here / "schema.sql").read_text(encoding="utf-8")
tests = (here / "test.sql").read_text(encoding="utf-8")
bundle = "\n".join([
    "-- GENERATED by bundle_tests.py. Do not edit. Safe on live data: ends in rollback.",
    "begin;",
    "drop schema if exists fy cascade;",
    schema,
    tests,
    "rollback;",
    "",
])
(here / "test.bundle.sql").write_text(bundle, encoding="utf-8")
print("wrote test.bundle.sql", len(bundle), "bytes")
