-- GENERATED by bundle_tests.py. Do not edit. Safe on live data: ends in rollback.
begin;
drop schema if exists fy cascade;
-- ===== Farmyard Hub schema. Idempotent: safe to re-run. =====
-- pg_cron is enabled by RAY in the dashboard (Database → Extensions) before this runs.
create schema if not exists fy;
grant usage on schema fy to anon, authenticated;

-- 1. Tables ----------------------------------------------------------------
create table if not exists fy.league (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  public_badges boolean not null default true,
  auto_confirm_days int not null default 14,
  created_at timestamptz not null default now()
);

create table if not exists fy.member (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references fy.league(id),
  nickname text not null,
  avatar text not null default 'hen',
  user_id uuid unique references auth.users(id),
  discord_id text,
  role text not null default 'member' check (role in ('leader','member')),
  chesscom_username text,
  created_at timestamptz not null default now(),
  unique (league_id, nickname)
);

-- Claim tokens live apart from member so no page can ever read them.
create table if not exists fy.claim_link (
  token text primary key default replace(gen_random_uuid()::text, '-', ''),
  member_id uuid not null references fy.member(id),
  created_at timestamptz not null default now(),
  used_at timestamptz
);

create table if not exists fy.event_type (
  key text not null,
  league_id uuid not null references fy.league(id),
  label text not null,
  points_rule jsonb not null default '{"rule":"winner_takes_all"}',
  overall_weight numeric not null default 1,
  primary key (league_id, key)
);

create table if not exists fy.event (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references fy.league(id),
  type_key text not null,
  played_at timestamptz not null default now(),
  entered_by uuid references fy.member(id),
  note text,
  voided_at timestamptz,
  created_at timestamptz not null default now(),
  foreign key (league_id, type_key) references fy.event_type(league_id, key)
);

create table if not exists fy.score_entry (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references fy.league(id),
  event_id uuid references fy.event(id),
  member_id uuid not null references fy.member(id),
  points int not null,
  reason text not null check (reason in ('result','correction','claim')),
  created_at timestamptz not null default now()
);

create table if not exists fy.settlement (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references fy.league(id),
  member_a uuid not null references fy.member(id),
  member_b uuid not null references fy.member(id),
  settled_at timestamptz not null default now(),
  recorded_by uuid references fy.member(id)
);

create table if not exists fy.iou (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references fy.league(id),
  event_id uuid references fy.event(id),
  payer_id uuid not null references fy.member(id),
  payee_id uuid not null references fy.member(id),
  amount int not null check (amount > 0),
  state text not null default 'open'
    check (state in ('open','marked_paid','confirmed','disputed','settled')),
  state_changed_at timestamptz not null default now(),
  settlement_id uuid references fy.settlement(id),
  created_at timestamptz not null default now(),
  check (payer_id <> payee_id)
);

create table if not exists fy.claim (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references fy.league(id),
  member_id uuid not null references fy.member(id),
  payload jsonb not null,
  state text not null default 'pending' check (state in ('pending','approved','rejected')),
  decided_by uuid references fy.member(id),
  decided_at timestamptz,
  created_at timestamptz not null default now()
);

-- Seed: one league, three event types. Re-runnable.
insert into fy.league (slug, name) values ('farmyard', 'The Farmyard')
  on conflict (slug) do nothing;
insert into fy.event_type (league_id, key, label, overall_weight)
select l.id, v.key, v.label, v.w from fy.league l,
  (values ('poker','Poker',1), ('chess','Chess',1), ('super6','Super 6',0)) as v(key,label,w)
where l.slug = 'farmyard'
on conflict do nothing;

-- 2. Views -----------------------------------------------------------------
create or replace view fy.v_members_public as
  select id, league_id, nickname, avatar from fy.member;

-- Every score_entry has an event (decide_claim creates one for approved points claims),
-- so standings are a sum over events of each type.
create or replace view fy.v_standings as
  select m.league_id, t.key as type_key, m.id as member_id, m.nickname, m.avatar,
         coalesce((
           select sum(s.points) from fy.score_entry s
           join fy.event e on e.id = s.event_id
           where s.member_id = m.id and e.type_key = t.key and e.league_id = m.league_id
         ), 0)::int as points
  from fy.member m
  join fy.event_type t on t.league_id = m.league_id;

create or replace view fy.v_overall as
  select s.league_id, s.member_id, s.nickname, s.avatar,
         sum(s.points * t.overall_weight)::numeric(10,2) as points
  from fy.v_standings s
  join fy.event_type t on t.league_id = s.league_id and t.key = s.type_key
  group by s.league_id, s.member_id, s.nickname, s.avatar;

-- Live IOU = still counts against the payer.
create or replace view fy.v_live_iou as
  select * from fy.iou where state in ('open','marked_paid','disputed');

create or replace view fy.v_badges as
  select m.league_id, m.id as member_id,
         coalesce((select sum(amount) from fy.v_live_iou i where i.payer_id = m.id), 0)::int as owes,
         coalesce((select sum(amount) from fy.v_live_iou i where i.payee_id = m.id), 0)::int as owed
  from fy.member m
  join fy.league l on l.id = m.league_id
  where l.public_badges;

create or replace view fy.v_netting as
  select league_id,
         least(payer_id, payee_id) as member_a,
         greatest(payer_id, payee_id) as member_b,
         sum(case when payer_id < payee_id then amount else -amount end)::int as net
  from fy.v_live_iou
  group by league_id, least(payer_id, payee_id), greatest(payer_id, payee_id);
-- net > 0 means member_a owes member_b that many buy-ins; net < 0 the other way.

grant select on fy.v_members_public, fy.v_standings, fy.v_overall, fy.v_badges to anon, authenticated;
-- v_netting and v_live_iou are deliberately NOT granted: views run as their owner and would
-- bypass the iou row-level security. The leader reads netting through fy.netting() (Task 4).

-- 3. Functions ---------------------------------------------------------------
-- Every write goes through here. All are security definer and check the caller.

create or replace function fy.me() returns fy.member
language sql stable security definer set search_path = fy, public as $$
  select * from fy.member where user_id = auth.uid() limit 1;
$$;

create or replace function fy.is_leader() returns boolean
language sql stable security definer set search_path = fy, public as $$
  select exists (select 1 from fy.member where user_id = auth.uid() and role = 'leader');
$$;

-- Used by the member read policy: a policy on fy.member cannot query fy.member itself
-- (infinite recursion), so the check lives in a security-definer function.
create or replace function fy.is_member() returns boolean
language sql stable security definer set search_path = fy, public as $$
  select exists (select 1 from fy.member where user_id = auth.uid());
$$;

create or replace function fy._league() returns uuid
language sql stable set search_path = fy, public as $$
  select id from fy.league where slug = 'farmyard';
$$;

create or replace function fy._require_leader() returns fy.member
language plpgsql stable security definer set search_path = fy, public as $$
declare m fy.member;
begin
  select * into m from fy.member where user_id = auth.uid() and role = 'leader';
  if m.id is null then raise exception 'not allowed' using errcode = '42501'; end if;
  return m;
end $$;

create or replace function fy.create_member(p_nickname text, p_avatar text) returns uuid
language plpgsql security definer set search_path = fy, public as $$
declare v_id uuid;
begin
  perform fy._require_leader();
  insert into fy.member (league_id, nickname, avatar) values (fy._league(), p_nickname, coalesce(p_avatar,'hen'))
  returning id into v_id;
  return v_id;
end $$;

create or replace function fy.issue_claim_link(p_member_id uuid) returns text
language plpgsql security definer set search_path = fy, public as $$
declare v_token text;
begin
  perform fy._require_leader();
  insert into fy.claim_link (member_id) values (p_member_id) returning token into v_token;
  return v_token;
end $$;

create or replace function fy.claim_profile(p_token text) returns uuid
language plpgsql security definer set search_path = fy, public as $$
declare v_member uuid; v_discord text; n int;
begin
  if auth.uid() is null then raise exception 'sign in first' using errcode = '42501'; end if;
  if exists (select 1 from fy.member where user_id = auth.uid()) then
    raise exception 'already claimed a profile' using errcode = '23505';
  end if;
  -- Burn the token first, in one statement: two accounts racing on the same link cannot both pass.
  update fy.claim_link set used_at = now()
  where token = p_token and used_at is null
  returning member_id into v_member;
  if v_member is null then raise exception 'link used or unknown' using errcode = 'P0002'; end if;
  -- The Discord user id lives in auth.identities, not in the JWT.
  select provider_id into v_discord from auth.identities
  where user_id = auth.uid() and provider = 'discord' limit 1;
  update fy.member set user_id = auth.uid(), discord_id = v_discord
  where id = v_member and user_id is null;
  get diagnostics n = row_count;
  if n = 0 then raise exception 'link used or unknown' using errcode = 'P0002'; end if;
  return v_member;
end $$;

create or replace function fy.void_event(p_event uuid, p_note text default null) returns void
language plpgsql security definer set search_path = fy, public as $$
declare e fy.event;
begin
  perform fy._require_leader();
  select * into e from fy.event where id = p_event for update;
  if e.id is null then raise exception 'no such event' using errcode = 'P0002'; end if;
  if e.voided_at is not null then raise exception 'already voided'; end if;
  insert into fy.score_entry (league_id, event_id, member_id, points, reason)
  select league_id, event_id, member_id, -points, 'correction' from fy.score_entry where event_id = p_event;
  update fy.iou set state = 'settled', state_changed_at = now()
  where event_id = p_event and state in ('open','marked_paid','disputed');
  update fy.event set voided_at = now(), note = coalesce(note || ' · ', '') || 'voided: ' || coalesce(p_note, '')
  where id = p_event;
end $$;

create or replace function fy.netting() returns setof fy.v_netting
language sql stable security definer set search_path = fy, public as $$
  select * from fy.v_netting where fy.is_leader();
$$;

create or replace function fy.recent_events(p_limit int default 10) returns setof fy.event
language sql stable security definer set search_path = fy, public as $$
  select * from fy.event where fy.is_leader() order by played_at desc limit p_limit;
$$;

create or replace function fy.record_poker_result(
  p_players jsonb, p_winner uuid, p_played_at timestamptz default now(), p_note text default null
) returns uuid
language plpgsql security definer set search_path = fy, public as $$
declare leader fy.member; v_event uuid; v_total int := 0; p record; v_winner_present boolean := false;
begin
  leader := fy._require_leader();
  if jsonb_typeof(p_players) <> 'array' or jsonb_array_length(p_players) < 2 then
    raise exception 'need at least two players';
  end if;
  for p in select (x->>'member_id')::uuid as member_id, (x->>'buy_ins')::int as buy_ins
           from jsonb_array_elements(p_players) x loop
    if p.buy_ins is null or p.buy_ins <= 0 then raise exception 'buy-ins must be at least 1'; end if;
    if not exists (select 1 from fy.member where id = p.member_id and league_id = fy._league()) then
      raise exception 'unknown player %', p.member_id;
    end if;
    if p.member_id = p_winner then v_winner_present := true; end if;
    v_total := v_total + p.buy_ins;
  end loop;
  if not v_winner_present then raise exception 'winner must be one of the players'; end if;

  insert into fy.event (league_id, type_key, played_at, entered_by, note)
  values (fy._league(), 'poker', coalesce(p_played_at, now()), leader.id, p_note) returning id into v_event;

  insert into fy.score_entry (league_id, event_id, member_id, points, reason)
  values (fy._league(), v_event, p_winner, v_total, 'result');

  insert into fy.iou (league_id, event_id, payer_id, payee_id, amount)
  select fy._league(), v_event, (x->>'member_id')::uuid, p_winner, (x->>'buy_ins')::int
  from jsonb_array_elements(p_players) x
  where (x->>'member_id')::uuid <> p_winner;

  return v_event;
end $$;

create or replace function fy.iou_transition(p_iou uuid, p_to text) returns void
language plpgsql security definer set search_path = fy, public as $$
declare me fy.member; i fy.iou; ok boolean := false;
begin
  select * into me from fy.member where user_id = auth.uid();
  if me.id is null then raise exception 'sign in first' using errcode = '42501'; end if;
  select * into i from fy.iou where id = p_iou for update;
  if i.id is null then raise exception 'no such IOU' using errcode = 'P0002'; end if;
  if i.state in ('confirmed','settled') then raise exception 'already closed'; end if;

  if me.role = 'leader' then
    ok := p_to in ('open','marked_paid','confirmed','disputed');
  elsif me.id = i.payer_id then
    ok := (i.state = 'open' and p_to = 'marked_paid');
  elsif me.id = i.payee_id then
    ok := (i.state = 'marked_paid' and p_to in ('confirmed','disputed'));
  end if;
  if not ok then raise exception 'not allowed' using errcode = '42501'; end if;

  update fy.iou set state = p_to, state_changed_at = now() where id = p_iou;
end $$;

create or replace function fy.settle_pair(p_a uuid, p_b uuid) returns uuid
language plpgsql security definer set search_path = fy, public as $$
declare leader fy.member; v_id uuid;
begin
  leader := fy._require_leader();
  insert into fy.settlement (league_id, member_a, member_b, recorded_by)
  values (fy._league(), p_a, p_b, leader.id) returning id into v_id;
  update fy.iou set state = 'settled', settlement_id = v_id, state_changed_at = now()
  where state in ('open','marked_paid','disputed')
    and ((payer_id = p_a and payee_id = p_b) or (payer_id = p_b and payee_id = p_a));
  return v_id;
end $$;

create or replace function fy.raise_claim(p_payload jsonb) returns uuid
language plpgsql security definer set search_path = fy, public as $$
declare me fy.member; v_id uuid;
begin
  select * into me from fy.member where user_id = auth.uid();
  if me.id is null then raise exception 'sign in first' using errcode = '42501'; end if;
  if p_payload->>'type' not in ('points','iou') then raise exception 'claim type must be points or iou'; end if;
  insert into fy.claim (league_id, member_id, payload) values (fy._league(), me.id, p_payload) returning id into v_id;
  return v_id;
end $$;

create or replace function fy.decide_claim(p_claim uuid, p_approve boolean) returns void
language plpgsql security definer set search_path = fy, public as $$
declare leader fy.member; c fy.claim; v_event uuid;
begin
  leader := fy._require_leader();
  select * into c from fy.claim where id = p_claim and state = 'pending' for update;
  if c.id is null then raise exception 'no pending claim' using errcode = 'P0002'; end if;
  if p_approve then
    if c.payload->>'type' = 'points' then
      insert into fy.event (league_id, type_key, entered_by, note)
      values (fy._league(), c.payload->>'type_key', leader.id, 'claim ' || c.id) returning id into v_event;
      insert into fy.score_entry (league_id, event_id, member_id, points, reason)
      values (fy._league(), v_event, c.member_id, (c.payload->>'points')::int, 'claim');
    else
      insert into fy.iou (league_id, payer_id, payee_id, amount)
      values (fy._league(), (c.payload->>'payer_id')::uuid, (c.payload->>'payee_id')::uuid, (c.payload->>'amount')::int);
    end if;
  end if;
  update fy.claim set state = case when p_approve then 'approved' else 'rejected' end,
                      decided_by = leader.id, decided_at = now() where id = p_claim;
end $$;

create or replace function fy.set_league(p_public_badges boolean, p_auto_confirm_days int) returns void
language plpgsql security definer set search_path = fy, public as $$
begin
  perform fy._require_leader();
  update fy.league set public_badges = coalesce(p_public_badges, public_badges),
                      auto_confirm_days = coalesce(p_auto_confirm_days, auto_confirm_days)
  where id = fy._league();
end $$;

create or replace function fy.set_weight(p_key text, p_weight numeric) returns void
language plpgsql security definer set search_path = fy, public as $$
begin
  perform fy._require_leader();
  update fy.event_type set overall_weight = p_weight where league_id = fy._league() and key = p_key;
end $$;

create or replace function fy.auto_confirm_ious() returns int
language plpgsql security definer set search_path = fy, public as $$
declare n int;
begin
  update fy.iou i set state = 'confirmed', state_changed_at = now()
  from fy.league l
  where i.league_id = l.id and i.state = 'marked_paid'
    and i.state_changed_at < now() - make_interval(days => l.auto_confirm_days);
  get diagnostics n = row_count;
  return n;
end $$;

create or replace function fy.my_ious() returns setof fy.iou
language sql stable security definer set search_path = fy, public as $$
  select i.* from fy.iou i join fy.member m on m.user_id = auth.uid()
  where i.payer_id = m.id or i.payee_id = m.id or m.role = 'leader'
  order by i.created_at desc;
$$;

-- Expose RPCs. PostgREST only sees functions in exposed schemas; RAY adds fy to
-- API → Exposed schemas in the dashboard (Task 6).
grant execute on function fy.me, fy.is_leader, fy.is_member, fy.claim_profile, fy.iou_transition, fy.raise_claim, fy.my_ious to authenticated;
grant execute on function fy.create_member, fy.issue_claim_link, fy.record_poker_result, fy.void_event, fy.netting, fy.recent_events,
  fy.settle_pair, fy.decide_claim, fy.set_league, fy.set_weight to authenticated;
revoke all on function fy.auto_confirm_ious from public;

-- Nightly auto-confirm at 00:10 UTC. pg_cron upserts by job name, so this is re-runnable.
select cron.schedule('fy_auto_confirm', '10 0 * * *', $$select fy.auto_confirm_ious()$$);

-- 4. Row-level security -------------------------------------------------------
alter table fy.league enable row level security;
alter table fy.member enable row level security;
alter table fy.claim_link enable row level security;   -- no policies: nobody reads it directly
alter table fy.event_type enable row level security;
alter table fy.event enable row level security;
alter table fy.score_entry enable row level security;
alter table fy.iou enable row level security;
alter table fy.settlement enable row level security;
alter table fy.claim enable row level security;

grant select on fy.league, fy.event_type, fy.event, fy.score_entry to anon, authenticated;
grant select on fy.member, fy.iou, fy.settlement, fy.claim to authenticated;
grant update (nickname, avatar, chesscom_username) on fy.member to authenticated;

drop policy if exists league_read on fy.league;
create policy league_read on fy.league for select using (true);
drop policy if exists event_type_read on fy.event_type;
create policy event_type_read on fy.event_type for select using (true);
drop policy if exists event_read on fy.event;
create policy event_read on fy.event for select using (true);
drop policy if exists score_read on fy.score_entry;
create policy score_read on fy.score_entry for select using (true);

-- Only people with a claimed profile (or the leader) see member rows. "authenticated" alone is
-- any Discord account on the internet, not the crew.
drop policy if exists member_read on fy.member;
create policy member_read on fy.member for select to authenticated using (fy.is_member() or fy.is_leader());
drop policy if exists member_update_self on fy.member;
create policy member_update_self on fy.member for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists iou_read_party on fy.iou;
create policy iou_read_party on fy.iou for select to authenticated using (
  fy.is_leader() or exists (
    select 1 from fy.member m where m.user_id = auth.uid() and (m.id = payer_id or m.id = payee_id)));

drop policy if exists settlement_read_party on fy.settlement;
create policy settlement_read_party on fy.settlement for select to authenticated using (
  fy.is_leader() or exists (
    select 1 from fy.member m where m.user_id = auth.uid() and (m.id = member_a or m.id = member_b)));

drop policy if exists claim_read_own on fy.claim;
create policy claim_read_own on fy.claim for select to authenticated using (
  fy.is_leader() or exists (select 1 from fy.member m where m.user_id = auth.uid() and m.id = member_id));
-- No insert/update/delete policies anywhere: writes happen only inside security-definer functions.

-- Farmyard schema tests: the assertion body. Never run on its own. bundle_tests.py wraps it as
--   begin; drop schema if exists fy cascade; <schema.sql>; <this file>; rollback;
-- so it always runs on a fresh schema inside one transaction and leaves live data untouched.
-- Runs as postgres in the Supabase SQL editor, impersonating users via request.jwt.claims.
-- Any failed assertion raises, which aborts the transaction: the SQL editor shows the error.

-- Three fake auth users and their Discord identities, so claim_profile can read provider_id.
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'ray@test.local', '', '{"provider":"discord"}', '{}', now(), now()),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'sock@test.local', '', '{"provider":"discord"}', '{}', now(), now()),
  ('00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'stranger@test.local', '', '{"provider":"discord"}', '{}', now(), now());
insert into auth.identities (user_id, provider, provider_id, identity_data, last_sign_in_at, created_at, updated_at)
values
  ('00000000-0000-0000-0000-000000000001', 'discord', '111', '{"sub":"111"}', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000002', 'discord', '222', '{"sub":"222"}', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000003', 'discord', '333', '{"sub":"333"}', now(), now(), now());

-- Leader profile is made directly (bootstrap; in prod RAY runs this one insert in the SQL editor).
insert into fy.member (league_id, nickname, avatar, user_id, role)
values (fy._league(), 'RAY', 'cock', '00000000-0000-0000-0000-000000000001', 'leader');

create or replace function pg_temp.as_user(u uuid) returns void language sql as $$
  select set_config('request.jwt.claims', json_build_object('sub', u, 'role', 'authenticated')::text, true),
         set_config('role', 'authenticated', true);
$$;
create or replace function pg_temp.as_anon() returns void language sql as $$
  select set_config('request.jwt.claims', '', true), set_config('role', 'anon', true);
$$;
create or replace function pg_temp.as_owner() returns void language sql as $$
  select set_config('request.jwt.claims', '', true), set_config('role', 'postgres', true);
$$;

do $$
declare ray uuid; sock uuid; pants uuid; tok text; tok2 text; ev uuid; n int; i fy.iou; d text;
begin
  select id into ray from fy.member where nickname = 'RAY';

  -- Leader creates two unclaimed members and a claim link for Sock.
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000001');
  sock := fy.create_member('The Sock', 'sheep');
  pants := fy.create_member('Pants', 'pig');
  tok := fy.issue_claim_link(sock);

  -- Review focus 1: a night with an unclaimed loser still produces the IOU.
  ev := fy.record_poker_result(
    jsonb_build_array(jsonb_build_object('member_id', ray, 'buy_ins', 2),
                      jsonb_build_object('member_id', sock, 'buy_ins', 1),
                      jsonb_build_object('member_id', pants, 'buy_ins', 3)),
    ray, now(), 'first night');
  perform pg_temp.as_owner();
  select points into n from fy.v_standings where member_id = ray and type_key = 'poker';
  assert n = 6, 'winner points should be 6, got ' || n;
  select count(*) into n from fy.iou where event_id = ev;
  assert n = 2, 'two IOU rows expected';
  select owes into n from fy.v_badges where member_id = pants;
  assert n = 3, 'Pants owes 3';
  select owed into n from fy.v_badges where member_id = ray;
  assert n = 4, 'RAY owed 4';

  -- Review focus 2: bad nights write nothing.
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000001');
  begin
    perform fy.record_poker_result(jsonb_build_array(jsonb_build_object('member_id', ray, 'buy_ins', 1),
                                                     jsonb_build_object('member_id', sock, 'buy_ins', 1)), pants);
    raise exception 'should have failed: winner not a player';
  exception when others then
    if sqlerrm not like 'winner must be%' then raise; end if;
  end;
  begin
    perform fy.record_poker_result(jsonb_build_array(jsonb_build_object('member_id', ray, 'buy_ins', 0),
                                                     jsonb_build_object('member_id', sock, 'buy_ins', 1)), ray);
    raise exception 'should have failed: zero buy-in';
  exception when others then
    if sqlerrm not like 'buy-ins must be%' then raise; end if;
  end;
  perform pg_temp.as_owner();
  select count(*) into n from fy.event; assert n = 1, 'failed nights must not create events';

  -- Review focus 3: claim link works once, then never, for anyone.
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000002');
  assert fy.claim_profile(tok) = sock, 'Sock claims Sock';
  perform pg_temp.as_owner();
  select discord_id into d from fy.member where id = sock; assert d = '222', 'Discord id from auth.identities, got ' || coalesce(d, 'null');
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000003');  -- a stranger with the same link
  begin
    perform fy.claim_profile(tok);
    raise exception 'should have failed: second use by another account';
  exception when others then
    if sqlerrm not like 'link used%' then raise; end if;
  end;
  -- Stranger with no profile sees no member rows and no IOUs.
  select count(*) into n from fy.member; assert n = 0, 'stranger must not read members';
  select count(*) into n from fy.my_ious(); assert n = 0, 'stranger has no IOUs';
  select count(*) into n from fy.netting(); assert n = 0, 'stranger gets no netting';
  -- A second link for Pants, used by the stranger, works: that is the latecomer route.
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000001');
  tok2 := fy.issue_claim_link(pants);
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000003');
  assert fy.claim_profile(tok2) = pants, 'stranger becomes Pants via a fresh link';

  -- Review focus 4: wrong actor on an IOU.
  perform pg_temp.as_owner();
  select * into i from fy.iou where payer_id = sock and event_id = ev;
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000002');  -- Sock is the payer
  begin
    perform fy.iou_transition(i.id, 'confirmed');
    raise exception 'should have failed: payer cannot confirm';
  exception when others then
    if sqlerrm <> 'not allowed' then raise; end if;
  end;
  perform fy.iou_transition(i.id, 'marked_paid');
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000001');  -- RAY is the payee
  perform fy.iou_transition(i.id, 'confirmed');
  perform pg_temp.as_owner();
  select state into i.state from fy.iou where id = i.id; assert i.state = 'confirmed';
  select owed into n from fy.v_badges where member_id = ray; assert n = 3, 'RAY now owed 3 (Pants only)';

  -- RLS: Sock cannot read the Pants→RAY IOU; RAY (leader) can; anon reads standings only.
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000002');
  select count(*) into n from fy.iou where payer_id = pants; assert n = 0, 'Sock must not see Pants IOU';
  select count(*) into n from fy.my_ious(); assert n = 1, 'Sock sees exactly their own IOU';
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000001');
  select count(*) into n from fy.iou; assert n = 2, 'leader sees all';
  perform pg_temp.as_anon();
  select count(*) into n from fy.v_standings where type_key = 'poker'; assert n = 3, 'anon reads standings';
  begin
    select count(*) into n from fy.iou;
    raise exception 'anon must not read iou';
  exception when insufficient_privilege then null; end;

  -- Review focus 5: badges switch off hides v_badges but my_ious still works.
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000001');
  perform fy.set_league(false, null);
  perform pg_temp.as_anon();
  select count(*) into n from fy.v_badges; assert n = 0, 'no badges when switched off';
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000002');
  select count(*) into n from fy.my_ious(); assert n = 1, 'own IOUs still visible';
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000001');
  perform fy.set_league(true, null);

  -- Settlement closes the pair's live rows.
  perform fy.settle_pair(pants, ray);
  perform pg_temp.as_owner();
  select count(*) into n from fy.iou where state = 'settled'; assert n = 1, 'Pants row settled';

  -- Auto-confirm: back-date a marked_paid row.
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000001');
  ev := fy.record_poker_result(jsonb_build_array(jsonb_build_object('member_id', ray, 'buy_ins', 1),
                                                 jsonb_build_object('member_id', sock, 'buy_ins', 1)), ray);
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000002');
  select id into i.id from fy.my_ious() where event_id = ev;
  perform fy.iou_transition(i.id, 'marked_paid');
  perform pg_temp.as_owner();
  update fy.iou set state_changed_at = now() - interval '15 days' where id = i.id;
  assert fy.auto_confirm_ious() = 1, 'one row auto-confirmed';

  -- Claims: points claim lands as a score entry on approval.
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000002');
  i.id := fy.raise_claim('{"type":"points","type_key":"poker","points":2,"note":"side pot"}');
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000001');
  perform fy.decide_claim(i.id, true);
  perform pg_temp.as_owner();
  select points into n from fy.v_standings where member_id = sock and type_key = 'poker';
  assert n = 2, 'Sock has 2 points from the claim';

  -- Review focus 6: voiding a night reverses it.
  perform pg_temp.as_user('00000000-0000-0000-0000-000000000001');
  select points into n from fy.v_standings where member_id = ray and type_key = 'poker';  -- before
  ev := fy.record_poker_result(jsonb_build_array(jsonb_build_object('member_id', ray, 'buy_ins', 5),
                                                 jsonb_build_object('member_id', pants, 'buy_ins', 5)), pants);
  perform fy.void_event(ev, 'typo');
  perform pg_temp.as_owner();
  select points into d from fy.v_standings where member_id = ray and type_key = 'poker';
  assert d::int = n, 'RAY points back to ' || n;
  select points into d from fy.v_standings where member_id = pants and type_key = 'poker';
  assert d::int = 0, 'Pants back to 0 after void';
  select count(*) into n from fy.iou where event_id = ev and state = 'settled'; assert n = 1, 'voided night IOU closed';
  select count(*) into n from fy.event where id = ev and voided_at is not null; assert n = 1, 'event stamped voided';

  raise notice 'ALL TESTS PASSED';
end $$;

rollback;
